
function SP_ubs_acute_health_condition(){
	var destinedThead = ""
		+ "<div id=\"thead_id\" style=\"overflow:auto;\"> "
		+ "			<table id=\"table_id\" class=\"table table-striped table-bordered\"> "
		+ "				<thead> "
		+ "					<tr> "
		+ "						<th rowspan=\"2\">Acute Health Condition</th> "
		+ "						<th colspan=\"2\">Under-5(M)</th> "
		+ "						<th colspan=\"2\">Under-5(F)</th> "
		+ "						<th colspan=\"2\">6-17(M)</th> "
		+ "                        <th colspan=\"2\">6-17(F)</th> "
		+ "                        <th colspan=\"2\">18-49(M)</th> "
		+ "                        <th colspan=\"2\">18-49(F)</th> "
		+ "                        <th colspan=\"2\">50 and above(M)</th> "
		+ "                        <th colspan=\"2\">50 and above(F)</th> "
		+ "					</tr> "
		+ "					<tr> "
		+ "					 	<th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "					</tr> "
		+ "				</thead> "
		+ "				 "
		+ "			</table> "
		+ "			</div>";
	
	return destinedThead;
}


function SP_ubs_medical_and_other_distribute(){
	var destinedThead = ""
		+ "<div id=\"thead_id\" style=\"overflow:auto;\"> "
		+ "			<table id=\"table_id\" class=\"table table-striped table-bordered\"> "
		+ "				<thead> "
		+ "					<tr> "
		+ "						<th rowspan=\"2\">Acute Health Condition</th> "
		+ "						<th colspan=\"2\">Under-5(M)</th> "
		+ "						<th colspan=\"2\">Under-5(F)</th> "
		+ "						<th colspan=\"2\">6-17(M)</th> "
		+ "                        <th colspan=\"2\">6-17(F)</th> "
		+ "                        <th colspan=\"2\">18-49(M)</th> "
		+ "                        <th colspan=\"2\">18-49(F)</th> "
		+ "                        <th colspan=\"2\">50 and above(M)</th> "
		+ "                        <th colspan=\"2\">50 and above(F)</th> "
		+ "					</tr> "
		+ "					<tr> "
		+ "					 	<th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "					</tr> "
		+ "				</thead> "
		+ "				 "
		+ "			</table> "
		+ "			</div>";
	
	return destinedThead;
	
}

function SP_ubs_sexual_reproductive_health(){
	var destinedThead = ""
		+ "<div id=\"thead_id\" style=\"overflow:auto;\"> "
		+ "			<table id=\"table_id\" class=\"table table-striped table-bordered\"> "
		+ "				<thead> "
		+ "					<tr> "
		+ "						<th rowspan=\"2\">Sexual Reproductive Healt(SRH)</th> "
		+ "						<th colspan=\"2\">Adolescent(10-17)</th> "
		+ "						<th colspan=\"2\">Adult(18 and above)</th> "
		+ "		 "
		+ "					</tr> "
		+ "					<tr> "
		+ "					 	<th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                         "
		+ "					</tr> "
		+ "				</thead> "
		+ "				 "
		+ "			</table> "
		+ "			</div>";
	
	return destinedThead;
	
}

function SP_ubs_non_communicable_disease(){
	var destinedThead = ""
		+ "<div id=\"thead_id\" style=\"overflow:auto;\"> "
		+ "			<table id=\"table_id\" class=\"table table-striped table-bordered\"> "
		+ "				<thead> "
		+ "					<tr> "
		+ "						<th rowspan=\"2\">Non-communicable diseases</th> "
		+ "						<th colspan=\"2\">Under-5(M)</th> "
		+ "						<th colspan=\"2\">Under-5(F)</th> "
		+ "						<th colspan=\"2\">6-17(M)</th> "
		+ "                        <th colspan=\"2\">6-17(F)</th> "
		+ "                        <th colspan=\"2\">18-49(M)</th> "
		+ "                        <th colspan=\"2\">18-49(F)</th> "
		+ "                        <th colspan=\"2\">50 and above(M)</th> "
		+ "                        <th colspan=\"2\">50 and above(F)</th> "
		+ "					</tr> "
		+ "					<tr> "
		+ "					 	<th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "					</tr> "
		+ "				</thead> "
		+ "				 "
		+ "			</table> "
		+ "			</div>";
	
	return destinedThead;
}

function SP_ubs_injuries(){
	var destinedThead = ""
		+ "<div id=\"thead_id\" style=\"overflow:auto;\"> "
		+ "			<table id=\"table_id\" class=\"table table-striped table-bordered\"> "
		+ "				<thead> "
		+ "					<tr> "
		+ "						<th rowspan=\"2\">Injuries</th> "
		+ "						<th colspan=\"2\">Under-5(M)</th> "
		+ "						<th colspan=\"2\">Under-5(F)</th> "
		+ "						<th colspan=\"2\">6-17(M)</th> "
		+ "                        <th colspan=\"2\">6-17(F)</th> "
		+ "                        <th colspan=\"2\">18-49(M)</th> "
		+ "                        <th colspan=\"2\">18-49(F)</th> "
		+ "                        <th colspan=\"2\">50 and above(M)</th> "
		+ "                        <th colspan=\"2\">50 and above(F)</th> "
		+ "					</tr> "
		+ "					<tr> "
		+ "					 	<th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "					</tr> "
		+ "				</thead> "
		+ "				 "
		+ "			</table> "
		+ "			</div>";
	
	return destinedThead;
}

function SP_ubs_nutrition(){
	var destinedThead = ""
		+ "<div id=\"thead_id\" style=\"overflow:auto;\"> "
		+ "			<table id=\"table_id\" class=\"table table-striped table-bordered\"> "
		+ "				<thead> "
		+ "					<tr> "
		+ "						<th rowspan=\"2\">Nutrition Services</th> "
		+ "						<th colspan=\"2\">Under-5(M)</th> "
		+ "						<th colspan=\"2\">Under-5(F)</th> "
		+ "						<th colspan=\"2\">6-17(M)</th> "
		+ "                        <th colspan=\"2\">6-17(F)</th> "
		+ "                        <th colspan=\"2\">18-49(M)</th> "
		+ "                        <th colspan=\"2\">18-49(F)</th> "
		+ "                        <th colspan=\"2\">50 and above(M)</th> "
		+ "                        <th colspan=\"2\">50 and above(F)</th> "
		+ "					</tr> "
		+ "					<tr> "
		+ "					 	<th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "					</tr> "
		+ "				</thead> "
		+ "				 "
		+ "			</table> "
		+ "			</div>";
	
	return destinedThead;
}


function SP_ubs_mental_health(){
	var destinedThead = ""
		+ "<div id=\"thead_id\" style=\"overflow:auto;\"> "
		+ "			<table id=\"table_id\" class=\"table table-striped table-bordered\"> "
		+ "				<thead> "
		+ "					<tr> "
		+ "						<th rowspan=\"2\">Mental Health</th> "
		+ "						<th colspan=\"2\">Under-5(M)</th> "
		+ "						<th colspan=\"2\">Under-5(F)</th> "
		+ "						<th colspan=\"2\">6-17(M)</th> "
		+ "                        <th colspan=\"2\">6-17(F)</th> "
		+ "                        <th colspan=\"2\">18-49(M)</th> "
		+ "                        <th colspan=\"2\">18-49(F)</th> "
		+ "                        <th colspan=\"2\">50 and above(M)</th> "
		+ "                        <th colspan=\"2\">50 and above(F)</th> "
		+ "					</tr> "
		+ "					<tr> "
		+ "					 	<th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "					</tr> "
		+ "				</thead> "
		+ "				 "
		+ "			</table> "
		+ "			</div>";
	
	return destinedThead;
}

function SP_ubs_communicable_disease(){
	var destinedThead = ""
		+ "<div id=\"thead_id\" style=\"overflow:auto;\"> "
		+ "			<table id=\"table_id\" class=\"table table-striped table-bordered\"> "
		+ "				<thead> "
		+ "					<tr> "
		+ "						<th rowspan=\"2\">Communicable Diseases</th> "
		+ "						<th colspan=\"2\">Under-5(M)</th> "
		+ "						<th colspan=\"2\">Under-5(F)</th> "
		+ "						<th colspan=\"2\">6-17(M)</th> "
		+ "                        <th colspan=\"2\">6-17(F)</th> "
		+ "                        <th colspan=\"2\">18-49(M)</th> "
		+ "                        <th colspan=\"2\">18-49(F)</th> "
		+ "                        <th colspan=\"2\">50 and above(M)</th> "
		+ "                        <th colspan=\"2\">50 and above(F)</th> "
		+ "					</tr> "
		+ "					<tr> "
		+ "					 	<th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                         "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "                        <th>FDMN</th> "
		+ "					 	<th>HOST</th> "
		+ "					</tr> "
		+ "				</thead> "
		+ "				 "
		+ "			</table> "
		+ "			</div>";
	
	return destinedThead;
}